const $=id=>document.getElementById(id);let password='',config=null,dirty=false;
const status=(text)=>{$('status').textContent=text;};
async function request(path,method,data){const r=await fetch(path,{method,headers:{'Content-Type':'application/json',Authorization:'Bearer '+password},body:JSON.stringify(data||{}),cache:'no-store'});const result=await r.json();if(!r.ok)throw Error(result.error||'Unable to save changes.');return result;}
function field(label,value,type='text'){const l=document.createElement('label'),span=document.createElement('span'),input=document.createElement('input');span.textContent=label;input.type=type;if(type==='checkbox')input.checked=value;else {input.value=value;input.required=true;input.maxLength=60;}l.append(span,input);return l;}
function render(){['year','startDate','endDate','orderUrl'].forEach(k=>$(k).value=config[k]);$('rooms').replaceChildren();config.suites.forEach((s,i)=>{const row=document.createElement('div');row.className='room';const name=document.createElement('strong');name.textContent=s.name;const price=field('Total price',s.price),available=field('Available',s.available,'checkbox');price.querySelector('input').id='price-'+i;available.querySelector('input').id='available-'+i;row.append(name,price,available);$('rooms').append(row);});$('addons').replaceChildren();config.addons.forEach((a,i)=>{const l=field(a.t,a.p);l.querySelector('input').id='addon-'+i;$('addons').append(l);});}
$('login').onsubmit=async e=>{e.preventDefault();const b=e.target.querySelector('button');b.disabled=true;password=$('password').value;status('Connecting…');try{config=await request('/api/admin','POST');$('password').value='';render();$('login').hidden=true;$('editor').hidden=false;const readOnly=config.storageConfigured===false;$('editor').querySelectorAll('input').forEach(input=>input.disabled=readOnly);$('save').disabled=readOnly;status(readOnly?'Signed in. Settings are read-only until Google Sheets is connected.':'Connected. Changes are saved only when you press Save changes.');}catch(e){password='';status(e.message);}finally{b.disabled=false;}};
$('editor').oninput=()=>{dirty=true;status('Unsaved changes.');};
$('editor').onsubmit=async e=>{e.preventDefault();$('save').disabled=true;status('Saving…');try{const next={...config,year:Number($('year').value),startDate:$('startDate').value,endDate:$('endDate').value,orderUrl:$('orderUrl').value.trim(),suites:config.suites.map((s,i)=>({...s,price:$('price-'+i).value,available:$('available-'+i).checked})),addons:config.addons.map((a,i)=>({...a,p:$('addon-'+i).value}))};config=await request('/api/settings','PUT',next);dirty=false;status('Saved. Refresh the website to see your changes.');}catch(e){status(e.message);}finally{$('save').disabled=false;}};
$('logout').onclick=()=>{if(dirty&&!confirm('Discard unsaved changes?'))return;password='';config=null;dirty=false;$('editor').hidden=true;$('login').hidden=false;$('rooms').replaceChildren();status('Signed out.');};
window.addEventListener('beforeunload',e=>{if(dirty){e.preventDefault();e.returnValue='';}});
